### ISSUE TITLE
[style] Fix typo in almost each contract within SPDX-License-Identifier line

### ISSUE THREAD

**Issue by vsevdrob** [truhuis/truhuis-smart-contracts#36]
Each first line of almost every contract contain spelling mistake which has to be fixed:

From:

```sol
// SPDX-Licence-Identifier: MIT
```  

To:

```sol
// SPDX-License-Identifier: MIT
```

TL;DR The second letter 'c' inside of "Licence" must be replaced with the letter 's'.

**Comment by Opssy** [comment]
I will like to work on it
